In [2]:
#importing the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
#load the dataset

car=pd.read_csv("Cars.csv")

In [4]:
car.head()  # first 5 rows

HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

In [7]:
#rearranging the y col
car=car.iloc[:,[1,0,2,3,4]]

In [8]:
car

MPG   HP  VOL          SP         WT
0   53.700681   49   89  104.185353  28.762059
1   50.013401   55   92  105.461264  30.466833
2   50.013401   55   92  105.461264  30.193597
3   45.696322   70   92  113.461264  30.632114
4   50.504232   53   92  104.461264  29.889149
..        ...  ...  ...         ...        ...
76  36.900000  322   50  169.598513  16.132947
77  19.197888  238  115  150.576579  37.923113
78  34.000000  263   50  151.598513  15.769625
79  19.833733  295  119  167.944460  39.423099
80  12.101263  236  107  139.840817  34.948615

[81 rows x 5 columns]

In [9]:
#shap 
car.shape

(81, 5)

In [12]:
#duplicated
car.duplicated().sum()

0

In [13]:
#columns
car.columns

Index(['MPG', 'HP', 'VOL', 'SP', 'WT'], dtype='object')

In [14]:
#staistical analysis 

car.describe()

MPG          HP         VOL          SP         WT
count  81.000000   81.000000   81.000000   81.000000  81.000000
mean   34.422076  117.469136   98.765432  121.540272  32.412577
std     9.131445   57.113502   22.301497   14.181432   7.492813
min    12.101263   49.000000   50.000000   99.564907  15.712859
25%    27.856252   84.000000   89.000000  113.829145  29.591768
50%    35.152727  100.000000  101.000000  118.208698  32.734518
75%    39.531633  140.000000  113.000000  126.404312  37.392524
max    53.700681  322.000000  160.000000  169.598513  52.997752

In [15]:
#info
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   MPG     81 non-null     float64
 1   HP      81 non-null     int64  
 2   VOL     81 non-null     int64  
 3   SP      81 non-null     float64
 4   WT      81 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 3.3 KB


In [16]:
#missing values

car.isna().sum()

MPG    0
HP     0
VOL    0
SP     0
WT     0
dtype: int64

In [17]:
#corr
car.corr()

MPG        HP       VOL        SP        WT
MPG  1.000000 -0.725038 -0.529057 -0.687125 -0.526759
HP  -0.725038  1.000000  0.077459  0.973848  0.076513
VOL -0.529057  0.077459  1.000000  0.102170  0.999203
SP  -0.687125  0.973848  0.102170  1.000000  0.102439
WT  -0.526759  0.076513  0.999203  0.102439  1.000000

In [19]:
#extracting x and y
x=car.iloc[:,1:]
y=car.iloc[:,0]

In [20]:
x.head()

HP  VOL          SP         WT
0  49   89  104.185353  28.762059
1  55   92  105.461264  30.466833
2  55   92  105.461264  30.193597
3  70   92  113.461264  30.632114
4  53   92  104.461264  29.889149

In [21]:
y.head()

0    53.700681
1    50.013401
2    50.013401
3    45.696322
4    50.504232
Name: MPG, dtype: float64

In [23]:
#splitting the data into train and test

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [25]:
#linear regg model

from sklearn.linear_model import LinearRegression

lin_reg=LinearRegression()

lin_reg.fit(X_train,y_train)

LinearRegression()

In [27]:
#predciting on test data

test_pred=lin_reg.predict(X_test)

test_pred

array([38.18087139, 20.51144042, 37.80346811, 41.60822684, 16.53287115,
       34.2868925 , 49.46798902, 28.1412994 , 35.9948057 , 37.06814406,
       24.27199188, 48.76722983, 35.28188722, 32.34179338, 41.7937878 ,
       35.73745189, 35.04818643])

In [28]:
#
from sklearn import metrics
from sklearn.metrics import mean_squared_error

In [29]:
#acc

metrics.r2_score(y_test,test_pred)


0.6608649139501925

In [30]:
#Rmse
np.sqrt(mean_squared_error(y_test,test_pred))

5.312568429653167

# lasso

In [31]:
from sklearn.linear_model import Lasso,Ridge

In [32]:
#intializing the model
lso = Lasso(alpha=0.01,normalize=True)

In [33]:
#fit 
lso.fit(X_train,y_train)

C:\Users\Mohammed Azhar Uddin\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(


Lasso(alpha=0.01, normalize=True)

In [36]:
#prediction

lso_pred=lso.predict(X_test)

lso_pred

array([37.26717476, 21.47600427, 37.80775184, 41.02706026, 17.79824221,
       34.5561503 , 50.35541562, 29.50813008, 35.15708018, 38.64634868,
       24.50895798, 48.46351743, 34.27661755, 30.90308637, 41.93566453,
       37.14482734, 35.23949383])

In [38]:
#coef

lso.coef_

array([-0.15361146, -0.23256412,  0.22637047, -0.        ])

In [40]:
#
lso.alpha

0.01

In [41]:
#accuracy of lasso model

metrics.r2_score(y_test,lso_pred)

0.6844311188738899

In [42]:
#Rmse
np.sqrt(mean_squared_error(y_test,lso_pred))

5.1246624016336275

# ridge

In [43]:
#intialize your rmodel
rg=Ridge(alpha=0.01,normalize=True)

In [45]:
#fit
rg.fit(X_train,y_train)

C:\Users\Mohammed Azhar Uddin\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(


Ridge(alpha=0.01, normalize=True)

In [47]:
#predict

rg_pred=rg.predict(X_test)
rg_pred

array([37.50888744, 21.18794511, 37.69854668, 41.22018838, 17.41982437,
       34.59291216, 50.29010158, 29.29045975, 35.19901729, 38.1751307 ,
       24.46446446, 48.60824559, 34.5749402 , 31.46502674, 41.83235271,
       36.85015881, 35.11811271])

In [48]:
#coef
rg.coef_

array([-0.16528088, -0.14688629,  0.27741189, -0.26800329])

In [49]:
#accuracy


metrics.r2_score(y_test,rg_pred)

0.6746847776850657

In [50]:
#Rmse
np.sqrt(mean_squared_error(y_test,rg_pred))

5.203198187663971